import type { Incident, InjectionInput } from "../types/dashboard";

// Temporary presentation fixture. API/SSE wiring belongs here once packages/app exposes it.
export const incidents: Incident[] = [
  {
    id: "inc_adyen_br",
    status: "OPEN",
    severity: "CRITICAL",
    title: "Adyen · BR · CARD degradation",
    dimensions: "provider=Adyen · country=BR · payment_method=CARD",
    affectedMerchants: 4,
    startedAt: "14:03 UTC",
    costPerMinute: 412,
    recommendation: "Review routing capacity before shifting traffic.",
    evidence: { observedRate: 76.4, expectedRate: 93.8, ciLow: 72.1, ciHigh: 80.3, testedDimensions: ["provider", "country", "payment_method", "issuer"], rootCause: "provider=Adyen · country=BR · payment_method=CARD", suppressedEchoes: ["country=BR", "merchant=Shopline LatAm"] },
  },
  {
    id: "inc_issuer_mx",
    status: "OPEN",
    severity: "CRITICAL",
    title: "Issuer decline concentration in Mexico",
    dimensions: "merchant=Shopline LatAm · country=MX · issuer=BBVA",
    affectedMerchants: 1,
    startedAt: "14:08 UTC",
    costPerMinute: 206,
    recommendation: "Contact issuer operations and monitor decline mix.",
    evidence: { observedRate: 81.2, expectedRate: 94.8, ciLow: 76.6, ciHigh: 85.1, testedDimensions: ["merchant", "country", "issuer", "decline_code"], rootCause: "merchant=Shopline LatAm · country=MX · issuer=BBVA", suppressedEchoes: ["country=MX"], evidenceGap: "One low-volume sibling remains insufficient for attribution beyond this issuer." },
  },
  {
    id: "inc_pampa_ar",
    status: "OPEN",
    severity: "HIGH",
    title: "Pampa Foods · AR · CARD decline spike",
    dimensions: "merchant=Pampa Foods · country=AR · payment_method=CARD",
    affectedMerchants: 1,
    startedAt: "13:52 UTC",
    costPerMinute: 96,
    recommendation: "Compare acquirer response codes against the AR CARD baseline.",
    evidence: { observedRate: 74.2, expectedRate: 90.0, ciLow: 69.8, ciHigh: 78.4, testedDimensions: ["merchant", "country", "payment_method", "acquirer"], rootCause: "merchant=Pampa Foods · country=AR · payment_method=CARD", suppressedEchoes: [] },
  },
  {
    id: "inc_bemol_br",
    status: "OPEN",
    severity: "HIGH",
    title: "Bemol Digital · issuer timeout cluster",
    dimensions: "merchant=Bemol Digital · country=BR · decline_code=ISSUER_TIMEOUT",
    affectedMerchants: 1,
    startedAt: "13:41 UTC",
    costPerMinute: 58,
    recommendation: "Escalate to issuer ops; consider temporary retry backoff.",
    evidence: { observedRate: 86.1, expectedRate: 94.4, ciLow: 83.0, ciHigh: 89.0, testedDimensions: ["merchant", "country", "decline_code"], rootCause: "merchant=Bemol Digital · decline_code=ISSUER_TIMEOUT", suppressedEchoes: ["country=BR"] },
  },
  {
    id: "inc_dlocal_mx",
    status: "OPEN",
    severity: "MEDIUM",
    title: "dLocal · MX · CARD soft-decline rise",
    dimensions: "provider=dLocal · country=MX · payment_method=CARD",
    affectedMerchants: 2,
    startedAt: "13:30 UTC",
    costPerMinute: 34,
    recommendation: "Monitor; below the material-drop threshold for now.",
    evidence: { observedRate: 76.0, expectedRate: 84.0, ciLow: 72.5, ciHigh: 79.6, testedDimensions: ["provider", "country", "payment_method"], rootCause: "provider=dLocal · country=MX · payment_method=CARD", suppressedEchoes: [] },
  },
  {
    id: "inc_yunopix_settlement",
    status: "MONITORING",
    severity: "MEDIUM",
    title: "Yuno Pix · BR · settlement delay",
    dimensions: "provider=Yuno Pix · country=BR · payment_method=PIX",
    affectedMerchants: 3,
    startedAt: "13:12 UTC",
    costPerMinute: 19,
    recommendation: "No conversion impact yet; watching settlement confirmation latency.",
    evidence: { observedRate: 95.1, expectedRate: 96.0, ciLow: 93.8, ciHigh: 96.4, testedDimensions: ["provider", "country", "payment_method"], rootCause: "provider=Yuno Pix · country=BR · payment_method=PIX", suppressedEchoes: [], evidenceGap: "Delta is within the noise band; kept in monitoring rather than promoted to open." },
  },
  {
    id: "inc_kaya_mx",
    status: "OPEN",
    severity: "MEDIUM",
    title: "Kaya Foods · MX · issuer decline",
    dimensions: "merchant=Kaya Foods · country=MX · issuer=BBVA",
    affectedMerchants: 1,
    startedAt: "13:05 UTC",
    costPerMinute: 21,
    recommendation: "Low volume; continue monitoring alongside the Shopline MX cluster.",
    evidence: { observedRate: 88.8, expectedRate: 95.2, ciLow: 85.6, ciHigh: 91.6, testedDimensions: ["merchant", "country", "issuer"], rootCause: "merchant=Kaya Foods · country=MX · issuer=BBVA", suppressedEchoes: [] },
  },
  {
    id: "inc_shopline_ar",
    status: "OPEN",
    severity: "LOW",
    title: "Shopline LatAm · AR · 3DS friction increase",
    dimensions: "merchant=Shopline LatAm · country=AR · payment_method=CARD",
    affectedMerchants: 1,
    startedAt: "12:58 UTC",
    costPerMinute: 14,
    recommendation: "Track 3DS challenge rate; no action required yet.",
    evidence: { observedRate: 89.4, expectedRate: 92.0, ciLow: 87.0, ciHigh: 91.6, testedDimensions: ["merchant", "country", "payment_method"], rootCause: "merchant=Shopline LatAm · country=AR · payment_method=CARD", suppressedEchoes: [] },
  },
  {
    id: "inc_vendo_br",
    status: "OPEN",
    severity: "LOW",
    title: "Vendo · BR · acquirer routing timeout",
    dimensions: "merchant=Vendo · country=BR · decline_code=ACQUIRER_TIMEOUT",
    affectedMerchants: 1,
    startedAt: "12:44 UTC",
    costPerMinute: 11,
    recommendation: "Intermittent; revisit if frequency doubles in the next window.",
    evidence: { observedRate: 79.1, expectedRate: 86.5, ciLow: 75.2, ciHigh: 82.7, testedDimensions: ["merchant", "country", "decline_code"], rootCause: "merchant=Vendo · decline_code=ACQUIRER_TIMEOUT", suppressedEchoes: [] },
  },
  {
    id: "inc_nubi_issuer",
    status: "OPEN",
    severity: "LOW",
    title: "Nubi Store · BR · issuer soft decline",
    dimensions: "merchant=Nubi Store · country=BR · issuer=Itau",
    affectedMerchants: 1,
    startedAt: "12:30 UTC",
    costPerMinute: 8,
    recommendation: "Within normal variance; kept open for trend tracking.",
    evidence: { observedRate: 91.6, expectedRate: 92.7, ciLow: 89.9, ciHigh: 93.2, testedDimensions: ["merchant", "country", "issuer"], rootCause: "merchant=Nubi Store · issuer=Itau", suppressedEchoes: [] },
  },
  {
    id: "inc_adyen_mx_resolved",
    status: "RESOLVED",
    severity: "LOW",
    title: "Adyen · MX · CARD degradation",
    dimensions: "provider=Adyen · country=MX · payment_method=CARD",
    affectedMerchants: 2,
    startedAt: "yesterday · 09:14 UTC",
    costPerMinute: 0,
    recommendation: "Resolved after acquirer restored capacity; no further action.",
    evidence: { observedRate: 93.9, expectedRate: 94.1, ciLow: 92.4, ciHigh: 95.2, testedDimensions: ["provider", "country", "payment_method"], rootCause: "provider=Adyen · country=MX · payment_method=CARD", suppressedEchoes: [] },
  },
];

export function buildInjectedIncident(input: InjectionInput): Incident {
  const route = `${input.provider} · ${input.country} · ${input.paymentMethod}`;
  return { id: `sim_${Date.now()}`, status: "OPEN", severity: "MEDIUM", title: `${route} simulated degradation`, dimensions: `merchant=${input.merchant} · provider=${input.provider} · country=${input.country} · payment_method=${input.paymentMethod} · issuer=${input.issuer} · decline_code=${input.declineCode}`, affectedMerchants: 1, startedAt: "now · simulated", costPerMinute: 0, recommendation: "Simulation queued. Review the resulting evidence before any human action.", isSimulated: true, evidence: { observedRate: 0, expectedRate: 0, ciLow: 0, ciHigh: 0, testedDimensions: ["merchant", "provider", "country", "payment_method", "issuer", "decline_code"], rootCause: `Awaiting detector result for ${route}`, suppressedEchoes: [], evidenceGap: "This is a UI simulation; the backend detector has not evaluated it." } };
}
